import AptosLogo from "../assets/chains/aptos.svg";
import SuiLogo from "../assets/chains/sui.svg";
import ZetaLogo from "../assets/chains/zeta.svg";
import ShardeumLogo from "../assets/chains/shardeum.svg";

export const chainList = [
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "1",
    color: "#ecf0f1",
    defaultDecimals: 18,
    displayName: "Ethereum",
    enabled: true,
    feeAssets: [
      {
        blockchain: "ETHEREUM_MAINNET_MAINNET",
        symbol: "ETH",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://etherscan.io/address/{wallet}",
      blockExplorerUrls: ["https://etherscan.io"],
      chainName: "Ethereum",
      enableGasV2: true,
      infoType: "EvmMetaInfo",
      nativeCurrency: { decimals: 18, name: "ETH", symbol: "ETH" },
      rpcUrls: ["https://rpc.ankr.com/eth"],
      transactionUrl: "https://etherscan.io/tx/",
    },
    logo: "https://api.rango.exchange/blockchains/ethereum.svg",
    name: "ETHEREUM_MAINNET_MAINNET",
    shortName: "ETH",
    sort: 0,
    isTestnet: false,
    type: "EVM",
  },
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "5",
    color: "#ecf0f1",
    defaultDecimals: 18,
    displayName: "Ethereum Goerli",
    enabled: true,
    feeAssets: [
      {
        blockchain: "ETHEREUM_TESTNET_GOERLI",
        symbol: "ETH",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://goerli.etherscan.io/address/{wallet}",
      blockExplorerUrls: ["https://goerli.etherscan.io/"],
      chainName: "Ethereum Goerli Testnet",
      enableGasV2: true,
      infoType: "EvmMetaInfo",
      nativeCurrency: { decimals: 18, name: "ETH", symbol: "ETH" },
      rpcUrls: ["https://rpc.ankr.com/eth_goerli"],
      transactionUrl: "https://goerli.etherscan.io/tx/",
    },
    logo: "https://api.rango.exchange/i/hncTcy",
    name: "ETHEREUM_TESTNET_GOERLI",
    shortName: "Goerli ETH",
    sort: 1,
    isTestnet: true,
    type: "EVM",
  },
  {
    addressPatterns: ["^[1-9A-HJ-NP-Za-km-z]{32,44}$"],
    chainId: "testnet-beta",
    color: "#708DD2",
    defaultDecimals: 9,
    displayName: "Solana",
    enabled: true,
    feeAssets: [
      {
        blockchain: "SOLANA_MAINNET_MAINNET",
        symbol: "SOL",
        address: null,
      },
    ],
    info: {
      blockExplorerUrls: ["https://explorer.solana.com"],
      transactionUrl: "https://explorer.solana.com/tx/",
      rpcUrls: ["https://api.mainnet-beta.solana.com"],
    },
    logo: "https://api.rango.exchange/blockchains/solana.svg",
    name: "SOLANA_MAINNET_MAINNET",
    shortName: "Solana",
    sort: 17,
    isTestnet: false,
    type: "SOLANA",
  },
  {
    addressPatterns: ["^[1-9A-HJ-NP-Za-km-z]{32,44}$"],
    chainId: "testnet",
    color: "#708DD2",
    defaultDecimals: 9,
    displayName: "Solana Testnet",
    enabled: true,
    feeAssets: [
      {
        blockchain: "SOLANA_TESTNET_TESTNET",
        symbol: "SOL",
        address: null,
      },
    ],
    info: {
      blockExplorerUrls: ["https://explorer.solana.com"],
      transactionUrl: "https://explorer.solana.com/tx/",
      rpcUrls: ["https://api.testnet.solana.com"],
    },
    logo: "https://api.rango.exchange/blockchains/solana.svg",
    name: "SOLANA_TESTNET_TESTNET",
    shortName: "Solana Testnet",
    sort: 17,
    isTestnet: true,
    type: "SOLANA",
  },
  {
    addressPatterns: "0x[a-fA-F0-9]{64}",
    chainId: null,
    color: "#708DD2",
    defaultDecimals: 8,
    displayName: "Aptos",
    enabled: true,
    feeAssets: [
      {
        blockchain: "APTOS_MAINNET_MAINNET",
        symbol: "APT",
        address: null,
      },
    ],
    info: {
      blockExplorerUrls: ["https://explorer.aptoslabs.com"],
      transactionUrl: "https://explorer.aptoslabs.com/txn/",
      rpcUrls: ["https://fullnode.mainnet.aptoslabs.com"],
    },
    logo: AptosLogo,
    name: "APTOS_MAINNET_MAINNET",
    shortName: "APTOS",
    sort: 15,
    isTestnet: false,
    type: "APTOS",
  },
  {
    addressPatterns: "0x[a-fA-F0-9]{64}",
    chainId: "testnet-beta",
    color: "#708DD2",
    defaultDecimals: 8,
    displayName: "Aptos Testnet",
    enabled: true,
    feeAssets: [
      {
        blockchain: "APTOS_TESTNET_TESTNET",
        symbol: "APT",
        address: null,
      },
    ],
    info: {
      blockExplorerUrls: ["https://explorer.aptoslabs.com"],
      transactionUrl: "https://explorer.aptoslabs.com/txn/",
      rpcUrls: ["https://fullnode.testnet.aptoslabs.com"],
    },
    logo: AptosLogo,
    name: "APTOS_TESTNET_TESTNET",
    shortName: "APTOS Testnet",
    sort: 15,
    isTestnet: true,
    type: "APTOS",
  },
  {
    addressPatterns: "0x[a-fA-F0-9]{64}",
    chainId: null,
    color: "#708DD2",
    defaultDecimals: 9,
    displayName: "Sui",
    enabled: true,
    feeAssets: [
      {
        blockchain: "SUI_MAINNET_MAINNET",
        symbol: "SUI",
        address: null,
      },
    ],
    info: {
      blockExplorerUrls: ["https://suiexplorer.com/"],
      transactionUrl: "https://suiexplorer.com/address/",
    },
    logo: SuiLogo,
    name: "SUI_MAINNET_MAINNET",
    shortName: "SUI",
    sort: 15,
    isTestnet: false,
    type: "SUI",
  },
  {
    addressPatterns: "0x[a-fA-F0-9]{64}",
    chainId: null,
    color: "#708DD2",
    defaultDecimals: 9,
    displayName: "Sui Testnet",
    enabled: true,
    feeAssets: [
      {
        blockchain: "SUI_TESTNET_TESTNET",
        symbol: "SUI",
        address: null,
      },
    ],
    info: {
      blockExplorerUrls: ["https://suiexplorer.com/"],
      transactionUrl: "https://suiexplorer.com/address/?network=testnet",
    },
    logo: SuiLogo,
    name: "SUI_TESTNET_TESTNET",
    shortName: "SUI Testnet",
    sort: 15,
    isTestnet: true,
    type: "SUI",
  },
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "56",
    color: "#F3BA2F",
    defaultDecimals: 18,
    displayName: "BNB Smart Chain",
    enabled: true,
    feeAssets: [
      {
        blockchain: "BNB_MAINNET_MAINNET",
        symbol: "BNB",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://bscscan.com/address/{wallet}",
      blockExplorerUrls: ["https://bscscan.com"],
      transactionUrl: "https://bscscan.com/tx/",
      rpcUrls: ["https://bsc-dataseed.binance.org/"],
    },
    logo: "https://api.rango.exchange/blockchains/bsc.svg",
    name: "BNB_MAINNET_MAINNET",
    shortName: "BSC",
    sort: 1,
    isTestnet: false,
    type: "EVM",
  },
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "97",
    color: "#F3BA2F",
    defaultDecimals: 18,
    displayName: "BNB Testnet",
    enabled: true,
    feeAssets: [
      {
        blockchain: "BNB_TESTNET_TESTNET",
        symbol: "BNB",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://testnet.bscscan.com/address/{wallet}",
      blockExplorerUrls: ["https://testnet.bscscan.com"],
      transactionUrl: "https://testnet.bscscan.com/tx/",
      rpcUrls: ["https://data-seed-prebsc-1-s1.bnbchain.org:8545"],
    },
    logo: "https://api.rango.exchange/blockchains/bsc.svg",
    name: "BNB_TESTNET_TESTNET",
    shortName: "BSC Testnet",
    sort: 1,
    isTestnet: true,
    type: "EVM",
  },
  {
    addressPatterns: "^(0x)[0-9A-Fa-f]{40}$",
    chainId: "42161",
    color: "#28a0f0",
    defaultDecimals: 18,
    displayName: "Arbitrum",
    enabled: true,
    feeAssets: [
      {
        blockchain: "ARBITRUM_MAINNET_MAINNET",
        symbol: "ARB",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://arbiscan.io/address/{wallet}",
      blockExplorerUrls: "https://arbiscan.io",
      transactionUrl: "https://arbiscan.io/tx/",
      rpcUrls: ["https://arbitrum-mainnet.infura.io"],
    },
    logo: "https://api.rango.exchange/blockchains/arbitrum.svg",
    name: "ARBITRUM_MAINNET_MAINNET",
    shortName: "Arbitrum",
    sort: 2,
    isTestnet: false,
    type: "EVM",
  },
  {
    addressPatterns: "^(0x)[0-9A-Fa-f]{40}$",
    chainId: "421613",
    color: "#28a0f0",
    defaultDecimals: 18,
    displayName: "Arbitrum Goerli",
    enabled: true,
    feeAssets: [
      {
        blockchain: "ARBITRUM_TESTNET_GOERLI",
        symbol: "ARB",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://testnet.arbiscan.io//address/{wallet}",
      blockExplorerUrls: "https://testnet.arbiscan.io/",
      transactionUrl: "https://testnet.arbiscan.io//tx/",
      rpcUrls: ["https://goerli-rollup.arbitrum.io/rpc"],
    },
    logo: "https://api.rango.exchange/blockchains/arbitrum.svg",
    name: "ARBITRUM_TESTNET_GOERLI",
    shortName: "Arbitrum Goerli",
    sort: 2,
    isTestnet: true,
    type: "EVM",
  },
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "137",
    color: "#8247E5",
    defaultDecimals: 18,
    displayName: "Polygon",
    enabled: true,
    feeAssets: [
      {
        blockchain: "POLYGON_MAINNET_MAINNET",
        symbol: "MATIC",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://polygonscan.com/address/{wallet}",
      blockExplorerUrls: "https://polygonscan.com",
      transactionUrl: "https://polygonscan.com/tx/",
      rpcUrls: ["https://polygon-mainnet.infura.io"],
    },
    logo: "https://api.rango.exchange/blockchains/polygon.svg",
    name: "POLYGON_MAINNET_MAINNET",
    shortName: "Polygon",
    sort: 3,
    isTestnet: false,
    type: "EVM",
  },
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "80001",
    color: "#8247E5",
    defaultDecimals: 18,
    displayName: "Polygon Mumbai",
    enabled: true,
    feeAssets: [
      {
        blockchain: "POLYGON_TESTNET_MUMBAI",
        symbol: "MATIC",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://polygonscan.com/address/{wallet}",
      blockExplorerUrls: "https://mumbai.polygonscan.com",
      transactionUrl: "https://mumbai.polygonscan.com/tx/",
      rpcUrls: ["https://rpc-mumbai.maticvigil.com/"],
    },
    logo: "https://api.rango.exchange/blockchains/polygon.svg",
    name: "POLYGON_TESTNET_MUMBAI",
    shortName: "Polygon Mumbai",
    sort: 3,
    isTestnet: true,
    type: "EVM",
  },
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "10",
    color: "#FF0420",
    defaultDecimals: 18,
    displayName: "Optimism",
    enabled: true,
    feeAssets: [
      {
        blockchain: "OPTIMISM_MAINNET_MAINNET",
        symbol: "OP",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://optimistic.etherscan.io/address/{wallet}",
      blockExplorerUrls: "https://optimistic.etherscan.io",
      transactionUrl: "https://optimistic.etherscan.io/tx/",
      rpcUrls: ["https://optimism-mainnet.infura.io"],
    },
    logo: "https://api.rango.exchange/blockchains/optimism.svg",
    name: "OPTIMISM_MAINNET_MAINNET",
    shortName: "Optimisum",
    sort: 6,
    isTestnet: false,
    type: "EVM",
  },
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "420",
    color: "#FF0420",
    defaultDecimals: 18,
    displayName: "Optimism Goerli",
    enabled: true,
    feeAssets: [
      {
        blockchain: "OPTIMISM_TESTNET_GOERLI",
        symbol: "OP",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://goerli-explorer.optimism.io/address/{wallet}",
      blockExplorerUrls: "https://goerli-explorer.optimism.io",
      transactionUrl: "https://goerli-explorer.optimism.io/tx/",
      rpcUrls: ["https://goerli.optimism.io"],
    },
    logo: "https://api.rango.exchange/blockchains/optimism.svg",
    name: "OPTIMISM_TESTNET_GOERLI",
    shortName: "Optimisum Goerli",
    sort: 6,
    isTestnet: true,
    type: "EVM",
  },
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "43114",
    color: "#e84142",
    defaultDecimals: 18,
    displayName: "Avalanche",
    enabled: true,
    feeAssets: [
      {
        blockchain: "AVALANCHE_MAINNET_CCHAIN",
        symbol: "AVAX",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://subnets.avax.network//address/",
      blockExplorerUrls: "https://subnets.avax.network/",
      transactionUrl: "https://subnets.avax.network//tx/",
      rpcUrls: ["https://avalanche-mainnet.infura.io"],
    },
    logo: "https://api.rango.exchange/blockchains/avax_cchain.svg",
    name: "AVALANCHE_MAINNET_CCHAIN",
    shortName: "Avax",
    sort: 7,
    isTestnet: false,
    type: "EVM",
  },
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "43113",
    color: "#e84142",
    defaultDecimals: 18,
    displayName: "Avalanche Fuji",
    enabled: true,
    feeAssets: [
      {
        blockchain: "AVALANCHE_TESTNET_FUJI",
        symbol: "AVAX",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://testnet.snowtrace.io/address/{wallet}",
      blockExplorerUrls: "https://testnet.snowtrace.io",
      transactionUrl: "https://testnet.snowtrace.io/tx/",
      rpcUrls: ["https://api.avax-test.network/ext/bc/C/rpc"],
    },
    logo: "https://api.rango.exchange/blockchains/avax_cchain.svg",
    name: "AVALANCHE_TESTNET_FUJI",
    shortName: "Avalanche Fuji",
    sort: 7,
    isTestnet: true,
    type: "EVM",
  },
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "100",
    color: "#3E6957",
    defaultDecimals: 18,
    displayName: "Gnosis",
    enabled: false,
    feeAssets: [
      {
        blockchain: "GNOSIS_MAINNET_MAINNET",
        symbol: "GNO",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://gnosisscan.io/address/",
      blockExplorerUrls: "https://gnosisscan.io/",
      transactionUrl: "https://gnosisscan.io//tx/",
      rpcUrls: ["https://rpc.gnosischain.com"],
    },
    logo: "https://api.rango.exchange/blockchains/gnosis.svg",
    name: "GNOSIS_MAINNET_MAINNET",
    shortName: "Gnosis",
    sort: 45,
    isTestnet: false,
    type: "EVM",
  },
  {
    addressPatterns: ["^(0x)[0-9A-Fa-f]{40}$"],
    chainId: "10200",
    color: "#3E6957",
    defaultDecimals: 18,
    displayName: "Gnosis Chiado",
    enabled: false,
    feeAssets: [
      {
        blockchain: "GNOSIS_TESTNET_CHIADO",
        symbol: "XDAI",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://gnosis-chiado.blockscout.com//address/",
      blockExplorerUrls: "https://gnosis-chiado.blockscout.com",
      transactionUrl: "https://gnosis-chiado.blockscout.com/tx/",
      rpcUrls: ["https://rpc.chiadochain.net"],
    },
    logo: "https://api.rango.exchange/blockchains/gnosis.svg",
    name: "GNOSIS_TESTNET_CHIADO",
    shortName: "Gnosis Chiado",
    sort: 45,
    isTestnet: false,
    type: "EVM",
  },
  {
    addressPatterns: null,
    chainId: "8082",
    color: "#3E6957",
    defaultDecimals: 18,
    displayName: "Shardeum Betanet",
    enabled: false,
    feeAssets: [
      {
        blockchain: "SHARDEUM_BETANET_SPHINX",
        symbol: "SHM",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://explorer-sphinx.shardeum.org/account",
      blockExplorerUrls: "https://explorer-sphinx.shardeum.org",
      transactionUrl: "https://explorer-sphinx.shardeum.org/transaction/",
      rpcUrls: ["https://sphinx.shardeum.org/"],
    },
    logo: ShardeumLogo,
    name: "SHARDEUM_BETANET_SPHINX",
    shortName: "Shardeum Betanet",
    sort: 46,
    isTestnet: true,
    type: "EVM",
  },
  {
    addressPatterns: null,
    chainId: "7001",
    color: "#3E6957",
    defaultDecimals: 18,
    displayName: "ZetaChain Athens Testnet",
    enabled: false,
    feeAssets: [
      {
        blockchain: "ZETA_TESTNET_ATHENS",
        symbol: "aZETA",
        address: null,
      },
    ],
    info: {
      addressUrl: "https://explorer.zetachain.com",
      blockExplorerUrls: "https://explorer.zetachain.com",
      transactionUrl: "https://explorer.zetachain.com/evm/tx/",
      rpcUrls: ["https://rpc.ankr.com/zetachain_evm_athens_testnet"],
    },
    logo: ZetaLogo,
    name: "ZETA_TESTNET_ATHENS",
    shortName: "Zeta Testnet",
    sort: 47,
    isTestnet: true,
    type: "EVM",
  },
];
